.TH "apisamplecode::APISampleCode" 3 "Mon Feb 4 2013" "NScAPICode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apisamplecode::APISampleCode \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
franclin 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void apisamplecode.APISampleCode.main (String[]args)\fC [static]\fP"\fBParameters:\fP
.RS 4
\fIargs\fP the command line arguments 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NScAPICode from the source code.
