.TH "apisamplecode::NScAPIWrapper" 3 "Mon Feb 4 2013" "NScAPICode" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apisamplecode::NScAPIWrapper \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNScAPIWrapper\fP (String key, String userid, String webstoreUrl)"
.br
.ti -1c
.RI "String \fBgetUserID\fP ()"
.br
.ti -1c
.RI "void \fBgetCustomerDetails\fP (String email)"
.br
.ti -1c
.RI "void \fBgetShippingOptions\fP (HashMap parameters)"
.br
.ti -1c
.RI "void \fBgetShippingAndTax\fP (HashMap parameters)"
.br
.ti -1c
.RI "void \fBgetTaxForAnOrder\fP (HashMap parameters)"
.br
.ti -1c
.RI "void \fBinsertWebOrders\fP (HashMap parameters)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
franclin 
.RE
.PP
\fBDate:\fP
.RS 4
04/02/2013 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "apisamplecode.NScAPIWrapper.NScAPIWrapper (Stringkey, Stringuserid, StringwebstoreUrl)"This is the constructor of the class Three parameters are needed to build an object of this type
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP this represents your private. You should contact the NitroSell Support Team to request one. 
.br
\fIuserid\fP this represents your User ID as assigned by the retailer to which you would like to query his data 
.br
\fIwebstoreUrl\fP this is the URL of the WebStore that you would like to query 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void apisamplecode.NScAPIWrapper.getCustomerDetails (Stringemail)"This method is the endpoint to get the customer details 
.PP
\fBParameters:\fP
.RS 4
\fIemail\fP 
.RE
.PP

.SS "void apisamplecode.NScAPIWrapper.getShippingAndTax (HashMapparameters)"This method is the endpoint to get the list of shipping options and any applicable tax The parameters of the request are passed in parameters tables 
.PP
\fBParameters:\fP
.RS 4
\fIparameters\fP 
.RE
.PP

.SS "void apisamplecode.NScAPIWrapper.getShippingOptions (HashMapparameters)"This method is the endpoint to get the list of shipping options The parameters of the request are passed in parameters tables 
.PP
\fBParameters:\fP
.RS 4
\fIparameters\fP 
.RE
.PP

.SS "void apisamplecode.NScAPIWrapper.getTaxForAnOrder (HashMapparameters)"This method is the endpoint to get the tax for a given order The parameters of the request are passed in parameters tables 
.PP
\fBParameters:\fP
.RS 4
\fIparameters\fP 
.RE
.PP

.SS "String apisamplecode.NScAPIWrapper.getUserID ()"This method returns the user ID
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "void apisamplecode.NScAPIWrapper.insertWebOrders (HashMapparameters)"This method is the endpoint to insert an order into the WebStore The parameters of the request are passed in parameters tables 
.PP
\fBParameters:\fP
.RS 4
\fIparameters\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NScAPICode from the source code.
